prereqs: do not attempt to install docker when its already installed with dcos-ansible
dcos/dcos-ansible pull request #19
Opened 2019-04-06 00:18 UTC by bernadinm

Without this change, this will attempt to install docker. This is to not fail if docker already exist. i

A better longer optimization I suggest here is that we should look to see if we can conditionally perform prereq matching with dcos_version that is based on the supported matrix here: https://docs.mesosphere.com/version-policy/

This change should be reasonable for the time being.

### After: 

```
TASK [DCOS.requirements : Finding RHEL extras repository name (Only EL systems)] ********************************************
skipping: [54.188.208.81]
skipping: [54.188.175.78]
skipping: [54.212.46.61]
skipping: [35.166.83.77]
skipping: [54.70.0.23]
skipping: [18.237.58.142]
skipping: [54.202.19.56]

TASK [DCOS.requirements : Docker installed] *********************************************************************************
changed: [18.237.58.142]
changed: [54.212.46.61]
changed: [54.188.175.78]
changed: [35.166.83.77]
changed: [54.70.0.23]
changed: [54.188.208.81]
changed: [54.202.19.56]

TASK [DCOS.requirements : Docker running (Only on some platforms)] **********************************************************
changed: [54.188.175.78]
changed: [54.188.208.81]
changed: [18.237.58.142]
changed: [54.212.46.61]
changed: [54.70.0.23]
changed: [35.166.83.77]
changed: [54.202.19.56]
```

### Before

```
TASK [DCOS.requirements : Docker installed] 
FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
fatal: [34.212.177.54]: FAILED! => {"attempts": 3, "changed": false, "msg": "Error: docker-ce-cli conflicts with 2:docker-1.13.1-94.gitb2f74b2.el7.centos.x86_64\nError: docker-ce conflicts with 2:docker-1.13.1-94.gitb2f74b2.el7.centos.x86_64\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: centos.s.uw.edu\n * extrfatal: [34.212.177.54]: FAILED! => {"attemp                                           FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
fatal: [34.212.177.54]: FAILED! => {"attempts": 3, "changed": false, "msg": "Error: docker-ce-cli conflicts with 2:docker-1.13.1-94.gitb2f74b2.el7.centos.x86_64\nError: docker-ce conflicts with 2:docker-1.13.1-94.gitb2f74b2.el7.centos.x86_64\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: centos.s.uw.edu\n * extrfatal: [34.212.177.54]: FAILED! => {"attempts": 3, "Refatal: [34.212.177.54]: FAILED! => {"attempt                                           FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (2 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
FAILED - RETRYING: Docker installed (1 retries left).
```

2019-04-06 00:20 UTC, AmrAbdelrazik commented
Nice work @bernadinm

2019-04-08 08:32 UTC, fatz requested changes
I see two(three) possible improvements here. 

Either make use of `package_facts` or have a set_facts task taking care of the condition, so tasks could check e.g. `docker_installed`.

The third option could be a mix of both which will enable us having further conditions like package version etc.

2019-04-08 08:32 UTC, fatz commented on roles/DCOS.requirements/tasks/main.yml
> +  register: yum_list
i think `yum_list` is to unspecific. In this particular case at least something like `yum_list_docker` should be used.

2019-04-08 08:32 UTC, fatz commented on roles/DCOS.requirements/tasks/main.yml
> +  # If not installed yum_list.results[*].yumstate != installed
the comment should be removed at this point. Even better its meaning should be ported into a task.

2019-04-08 08:32 UTC, fatz commented on roles/DCOS.requirements/tasks/main.yml
> +  when: ansible_distribution == 'CentOS' and yum_list.results | selectattr("yumstate", "match", "installed") | list | length == 0
This condition should be moved into its own set_fact.

2019-04-08 08:32 UTC, fatz commented on roles/DCOS.requirements/tasks/main.yml
> +      when: ansible_distribution != 'RedHat' and yum_list.results | selectattr("yumstate", "match", "installed") | list | length == 0
This condition should be moved into its own set_fact.

2019-04-16 17:01 UTC, merged