Revising PSK generation
dcos/dcos-ansible pull request #66
Opened 2019-09-03 17:40 UTC by jr0d

This is a second attempt at updating dcos-ansible to support PSK generation for Exhibitor TLS bootstrap.

2019-09-05 16:33 UTC, jr0d commented
Tested with universal installer:

```
$ ansible -i inventory all -m shell -a "stat /var/lib/dcos/.dcos-bootstrap-ca-psk" -u centos
54.245.219.12 | CHANGED | rc=0 >>
  File: ‘/var/lib/dcos/.dcos-bootstrap-ca-psk’
  Size: 16        	Blocks: 8          IO Block: 4096   regular file
Device: ca01h/51713d	Inode: 67109058    Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:var_lib_t:s0
Access: 2019-09-05 15:08:17.767303426 +0000
Modify: 2019-09-05 15:08:17.647306302 +0000
Change: 2019-09-05 15:08:17.771303330 +0000
 Birth: -

54.202.39.67 | CHANGED | rc=0 >>
  File: ‘/var/lib/dcos/.dcos-bootstrap-ca-psk’
  Size: 16        	Blocks: 8          IO Block: 4096   regular file
Device: ca01h/51713d	Inode: 67109058    Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:var_lib_t:s0
Access: 2019-09-05 15:04:21.821048800 +0000
Modify: 2019-09-05 15:04:21.703054371 +0000
Change: 2019-09-05 15:04:21.826048564 +0000
 Birth: -

34.216.251.149 | CHANGED | rc=0 >>
  File: ‘/var/lib/dcos/.dcos-bootstrap-ca-psk’
  Size: 16        	Blocks: 8          IO Block: 4096   regular file
Device: ca01h/51713d	Inode: 67109058    Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:var_lib_t:s0
Access: 2019-09-05 15:12:11.372351217 +0000
Modify: 2019-09-05 15:12:11.248352062 +0000
Change: 2019-09-05 15:12:11.376351190 +0000
 Birth: -
```

2019-09-05 16:50 UTC, sebbrandt87 commented on roles/dcos_bootstrap/tasks/main.yml
> +
extra empty line?

2019-09-05 16:57 UTC, sebbrandt87 requested changes
looking good, we would add tomorrow dcos-ansible enterprise test run to integrate that always running test also in CI

2019-09-05 16:57 UTC, sebbrandt87 commented on roles/dcos_bootstrap/tasks/main.yml
> +
extra empty line?

2019-09-05 16:57 UTC, sebbrandt87 commented on roles/dcos_bootstrap/tasks/main.yml
> +
extra empty line?

2019-09-05 18:39 UTC, jr0d commented on roles/dcos_bootstrap/tasks/main.yml
> +
not sure how those snuck in. fixing

2019-09-11 13:20 UTC, sebbrandt87 commented
test agains enterprise looking good
```TASK [dcos_bootstrap : Set PSK path] *******************************************
    ok: [bootstrap1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36]
    
    TASK [dcos_bootstrap : Stat the existing PSK] **********************************
    ok: [bootstrap1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36]
    
    TASK [dcos_bootstrap : Read existing PSK contents] *****************************
    ok: [bootstrap1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36]
    
    TASK [dcos_bootstrap : Generate PSK for exhibitor bootstrap] *******************
    skipping: [bootstrap1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36]
    
    TASK [dcos_bootstrap : Write CA service PSK] ***********************************
    skipping: [bootstrap1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36]
    
    TASK [dcos_bootstrap : Delegate psk variable from disk] ************************
    ok: [bootstrap1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36 -> 3.226.241.182] => (item=master1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36)
    
    TASK [dcos_bootstrap : Delegate psk variable from password generator] **********
    skipping: [bootstrap1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36] => (item=master1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36) 

...

TASK [dcos_master : Write CA service PSK] **************************************
    ok: [master1-centos7-enterprise-ci-mesos-jenkins-58d4b86021814e4b97865f9474daf0dd-py36]
```

2019-09-11 13:21 UTC, sebbrandt87 approved these changes

2019-09-11 14:11 UTC, merged